name: torch_rl_ad_optimization
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - ca-certificates=2024.12.31
  - openssl=3.0.15
  - pip=24.2
  - python=3.9.21
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tzdata=2025a
  - wheel=0.44.0
  - numpy=1.24.0
  - pandas=2.0.1
  - matplotlib=3.7.1
  - seaborn=0.12.1
  - pip:
      - av==13.1.0
      - cloudpickle==3.1.1
      - filelock==3.17.0
      - fsspec==2024.12.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - importlib-metadata==8.6.1
      - jinja2==3.1.5
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==1.26.4
      - orjson==3.10.15
      - packaging==24.2
      - pillow==11.1.0
      - pygame==2.1.0
      - sympy==1.13.1
      - tensordict==0.6.1
      - torch==2.6.0
      - torchvision==0.21.0
      - torchaudio==2.6.0
      - torchrl==0.6.0
      - typing-extensions==4.12.2
      - zipp==3.21.0
      - gymnasium==0.28.1
      - optuna==3.3.0
      - tensorboard==2.18.0
      - tqdm==4.65.0
